# name
title = "TOML Example"

# here is tables
# asd
# asd

[owner]
name = "Tom Preston-Werner"

[database]
enabled = 1
temp_targets = { cpu = 79.5, case = 72.0 }
a = "1"

[servers]
[servers.alpha]
ip = "10.0.0.1"
role = "frontend"

[servers.beta]
ip = "10.0.0.2"
role = "backend"